### ISSUE TITLE
Destination UID of a tincan packet forwarded to the controller is all zeros

### ISSUE THREAD

**Issue by ssabogal** [ipop-project/ipop-tincan#106]
Tincan packets (message type: ```\x02```) are forwarded to the controller for handling when a tincan link is not established.

This packet should contain the destination UID in bytes ```[2:42]```, however this part of the packet appears to be the null uid (all zeros).

For the structured peer-to-peer GVPN controller, this event appears to always occur. Fortunately, this issue is avoided since the destination IPv4 address is correct and can be used to resolve the destination UID.

**Comment by kyuhojeong** [comment]
"Tincan packets" can be forwarded without any tincan link. It is confusing because of its bad naming. "Tincan packets" are actually all the packets that are forwarded from local and remote peers. So the packet itself can be forwarded from the local tap device. And even more, if you set switchmode to 1, it will make all the L2 frames (DHCP, IGMP, SCP etc..) forwards to controller. You can simply ignore these frames for the time being.

**Comment by goldsoft8888** [comment]
Sometimes occur, local computer DHCP to obtain the IP, it is through the distal IPOP DHCP server distribution.
How to solve this?

**Comment by saumitraaditya** [comment]
srcUID[2:22] is observed to be all zeros for multicast messages. dstUID being all 0's is not believed to be an issue.
