### ISSUE TITLE
IPOP with switchmode and on-demand crashes

### ISSUE THREAD

**Issue by kyuhojeong** [ipop-project/ipop-tincan#98]
It is reported that GroupVPN with on-demand and switchmode crashes. We haven't consulted yet how to handle ARP in ondemand and switchmode. Brute force approach would be creating tincan for every ARP broadcast, which seems too expensive for ARP but would save traffic if an IPOP node does not have any client associated.

**Comment by goldsoft8888** [comment]
ARP conflict-related networking and multiple OPENWRT crashes, what new progress?

**Comment by goldsoft8888** [comment]
Traceback (most recent call last):
  File "./gvpn_controller.py", line 10, in <module>
    from ipoplib import *
  File "/xvpn/ipoplib.py", line 19, in <module>
    import keyring
ImportError: No module named keyring

**Comment by pstjuste** [comment]
You should be able to fix this by installing the python-keyring module

sudo apt-get install python-keyring

On Wed, May 20, 2015 at 12:45 PM, goldsoft8888 <notifications@github.com>
wrote:

> Traceback (most recent call last):
> File "./gvpn_controller.py", line 10, in
> from ipoplib import *
> File "/xvpn/ipoplib.py", line 19, in
> import keyring
> ImportError: No module named keyring
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipop-project/ipop-tincan/issues/98#issuecomment-103955317>
> .
>



-- 
Pierre St Juste

**Comment by goldsoft8888** [comment]
This issue has been resolved. Download keyring, copied to Python, I hope to help other people, thank you very much.

**Comment by goldsoft8888** [comment]
Restart OPENWRT, make all of the network off the network, this is still not resolved.
Analysis There are several possibilities:
1, ARP problem, other OPENWRT WAN MAC will bring to the local, and there are multiple MAC addresses are duplicated. Creating a conflict of ARP.
2, each OPENWRT as two routes, but the log will record WAN communications. I believe that, in addition to the public network is the LAN, this is normal?
3, from logs found between UDP and TCP constantly changing, the two co-righteousness also need?

4, is affected, and external network communication, there will be short-term disruptions. I checked the log OPENWRT itself and found some problems. I think this may be a bridge to bring influence.


This is the communication between WAN --- WAN:
-------------------------------------------------- -
ingle: Conn [ipop-tincan: 79hWX8Cs: 1: 0: local: udp: 10.255.0.139: 52426-> LwSuoH ++: 1: 0.99: local: udp: 10.255.0.147: 50247 | CR-I | 9112786455816584702 | 1]: Timed out after 19047 ms without a response, rtt = 100
Jingle: Conn [ipop-tincan: 79hWX8Cs: 1: 0: local: udp: 10.255.0.139: 52426-> LwSuoH ++: 1: 0.99: local: udp: 10.255.0.147: 50247 | CR-I | 9112786455816584702 | 1]: Timed out after 19053 ms without a response, rtt = 100
Jingle: Conn [ipop-tincan: 79hWX8Cs: 1: 0: local: udp: 10.255.0.139: 52426-> LwSuoH ++: 1: 0.99: local: udp: 10.255.0.147: 50247 | CR-I | 9112786455816584702 | 1]: Timed out after 19059 ms without a response, rtt = 100
Jingle: Conn [ipop-tincan: 79hWX8Cs: 1: 0: local: udp: 10.255.0.139: 52426-> LwSuoH ++: 1: 0.99: local: udp: 10.255.0.147: 50247 | CR-I | 9112786455816584702 | 1]: Timed out after 19075 ms without a response, rtt = 100
-------------------------------------------------- --------------------------------
Why local LAN IP with the remote OPENWRT the WAN IP communications?
172.172.0.1 ------- 192.168.1.2
----------------------------------------------
le: Conn [ipop-tincan: 8dmS6 + Er: 1: 0: local: udp: 172.172.0.1: 34324-> jKTQlLAW: 1: 0.86: local: udp: 192.168.1.2: 1024 | C - W | 7960146426186186239 | -]: Connection created
Jingle: Conn [ipop-tincan: 8dmS6 + Er: 1: 0: local: udp: 172.172.0.1: 34324-> vRbCHISS: 1: 0.86: stun: udp: 192.168.1.2: 36728 | C - W | 7960146426186186239 | -]: Connection created
Jingle: Conn [ipop-tincan: 8dmS6 + Er: 1: 0: local: udp: 172.172.0.1: 34324-> d4PK55ph: 1: 0.86: stun: udp: 172.172.2.1: 36311 | C - W | 7959864951209475583 | -]: Connection created

-------------------------------------------------- --------
This is the communication between the public network

ingle: Conn [ipop-tincan: mHqGZKU6: 1: 0: stun: udp: 124.239.87.36: 50565-> s95jzzba: 1: 0.78: stun: udp: 60.6.1.8: 39428 | CRWI | 7239289009957912062 | 2291]: Timing- out STUN ping 2aJQAxIRXTXr after 5001 ms
Jingle: Conn [ipop-tincan: M6WKkqK4: 1: 0: stun: udp: 124.239.87.36: 48246-> s95jzzba: 1: 0.78: stun: udp: 60.6.1.8: 39428 | CRWI | 7239007534981201406 | 1761]: Timing- out STUN ping yeTmr / k5puZ5 after 5000 ms
Jingle: Conn [ipop-tincan: mHqGZKU6: 1: 0: stun: udp: 124.239.87.36: 50565-> Yjxo + 3bg: 1: 0.78: stun: udp: 60.6.1.8: 33995 | CRWI | 7239289009958043134 | 166]: Timing-out STUN ping ZAubkefkHuQO after 5001 ms
Jingle: Conn [ipop-tincan: mHqGZKU6: 1: 0: stun: udp: 124.239.87.36: 50565-> s95jzzba: 1: 0.78: stun: udp: 60.6.1.8: 39428 | CRWI | 7239289009957912062 | 2291]: Timing- out STUN ping VWc06ZPu275m after 5001 ms
Jingle: Conn [ipop-tincan: M6WKkqK4: 1: 0: stun: udp: 124.239.87.36: 48246-> s95jzzba: 1: 0.78: stun: udp: 60.6.1.8: 39428 | CRWI | 7239007534981201406 | 1761]: Timing- out STUN ping
--------------------------------------------------

This is OPENWRT router log, there will be the following information when things go wrong, it is not normal.
I'm sure the network was originally normal and stable, just because OPENWRT reboot or re-run IPOP, it did appear.
-------------------------------------------------- --------------------
42.110000] br-lan: port 2 (ipop) entered forwarding state
[42.110000] br-lan: port 2 (ipop) entered forwarding state
[44.110000] br-lan: port 2 (ipop) entered forwarding state
[376.220000] eth0: port 4 link down
[377.930000] eth0: port 4 link up (100Mbps / Full duplex)
[384.080000] eth0: port 4 link down
[385.740000] eth0: port 4 link up (100Mbps / Full duplex)
[418.500000] eth0: port 4 link down
[420.140000] eth0: port 4 link up (100Mbps / Full duplex)
[426.710000] eth0: port 4 link down
[428.340000] eth0: port 4 link up (100Mbps / Full duplex)
[638.230000] eth0: port 4 link down
[639.870000] eth0: port 4 link up (100Mbps / Full duplex)
[641.600000] eth0: port 4 link down
[643.150000] eth0: port 4 link up (100Mbps / Full duplex)
[643.330000] eth0: port 4 link down
[645.040000] eth0: port 4 link up (100Mbps / Full duplex)
[645.190000] eth0: port 4 link down
[649.170000] eth0: port 4 link up (100Mbps / Full duplex)

**Comment by saumitraaditya** [comment]
Resolved
